# Generated by Django 4.2 on 2023-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Header Logo Image')),
                ('path1', models.CharField(max_length=25, verbose_name='Header Path 1')),
                ('path1_hy', models.CharField(max_length=25, null=True, verbose_name='Header Path 1')),
                ('path1_ru', models.CharField(max_length=25, null=True, verbose_name='Header Path 1')),
                ('path1_en', models.CharField(max_length=25, null=True, verbose_name='Header Path 1')),
                ('path2', models.CharField(max_length=25, verbose_name='Header Path 2')),
                ('path2_hy', models.CharField(max_length=25, null=True, verbose_name='Header Path 2')),
                ('path2_ru', models.CharField(max_length=25, null=True, verbose_name='Header Path 2')),
                ('path2_en', models.CharField(max_length=25, null=True, verbose_name='Header Path 2')),
                ('path3', models.CharField(max_length=25, verbose_name='Header Path 3')),
                ('path3_hy', models.CharField(max_length=25, null=True, verbose_name='Header Path 3')),
                ('path3_ru', models.CharField(max_length=25, null=True, verbose_name='Header Path 3')),
                ('path3_en', models.CharField(max_length=25, null=True, verbose_name='Header Path 3')),
                ('path4', models.CharField(max_length=25, verbose_name='Header Path 4')),
                ('path4_hy', models.CharField(max_length=25, null=True, verbose_name='Header Path 4')),
                ('path4_ru', models.CharField(max_length=25, null=True, verbose_name='Header Path 4')),
                ('path4_en', models.CharField(max_length=25, null=True, verbose_name='Header Path 4')),
                ('path5', models.CharField(max_length=25, verbose_name='Header Path 5')),
                ('path5_hy', models.CharField(max_length=25, null=True, verbose_name='Header Path 5')),
                ('path5_ru', models.CharField(max_length=25, null=True, verbose_name='Header Path 5')),
                ('path5_en', models.CharField(max_length=25, null=True, verbose_name='Header Path 5')),
            ],
        ),
    ]
