# Generated by Django 4.2 on 2023-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Header Image')),
                ('img_hy', models.ImageField(null=True, upload_to='images', verbose_name='Header Image')),
                ('img_ru', models.ImageField(null=True, upload_to='images', verbose_name='Header Image')),
                ('img_en', models.ImageField(null=True, upload_to='images', verbose_name='Header Image')),
                ('title', models.CharField(max_length=30, verbose_name='Header Title')),
                ('title_hy', models.CharField(max_length=30, null=True, verbose_name='Header Title')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Header Title')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Header Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Header SubTitle')),
                ('subtitle_hy', models.CharField(max_length=50, null=True, verbose_name='Header SubTitle')),
                ('subtitle_ru', models.CharField(max_length=50, null=True, verbose_name='Header SubTitle')),
                ('subtitle_en', models.CharField(max_length=50, null=True, verbose_name='Header SubTitle')),
                ('btn_name', models.CharField(max_length=25, verbose_name='Header Button Name')),
                ('btn_name_hy', models.CharField(max_length=25, null=True, verbose_name='Header Button Name')),
                ('btn_name_ru', models.CharField(max_length=25, null=True, verbose_name='Header Button Name')),
                ('btn_name_en', models.CharField(max_length=25, null=True, verbose_name='Header Button Name')),
            ],
        ),
    ]
