# Generated by Django 4.2 on 2023-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hometitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLeftContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40, verbose_name='Home Page Left Content Title 1')),
                ('title1_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1')),
                ('title1_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1')),
                ('title1_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1')),
                ('title2', models.CharField(max_length=40, verbose_name='Home Page Left Content Title 2')),
                ('title2_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2')),
                ('title2_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2')),
                ('title2_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2')),
                ('img', models.ImageField(upload_to='images', verbose_name='Home Page Image')),
            ],
            options={
                'verbose_name': 'HomePageLeftContent',
                'verbose_name_plural': 'HomePageLeftContent',
            },
        ),
        migrations.CreateModel(
            name='HomePageRightContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Home Page Right Content Title')),
                ('title_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Title')),
                ('title_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Title')),
                ('title_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Title')),
                ('date', models.CharField(max_length=40, verbose_name='Home Page Right Content Date')),
                ('date_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Date')),
                ('date_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Date')),
                ('date_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Date')),
                ('location', models.CharField(max_length=40, verbose_name='Home Page Right Content Location')),
                ('location_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Location')),
                ('location_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Location')),
                ('location_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content Location')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Home Page Right Content SubTitle')),
                ('subtitle_hy', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content SubTitle')),
                ('subtitle_ru', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content SubTitle')),
                ('subtitle_en', models.CharField(max_length=40, null=True, verbose_name='Home Page Right Content SubTitle')),
                ('text', models.TextField(verbose_name='Home Page Right Content Text')),
                ('text_hy', models.TextField(null=True, verbose_name='Home Page Right Content Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Home Page Right Content Text')),
                ('text_en', models.TextField(null=True, verbose_name='Home Page Right Content Text')),
            ],
            options={
                'verbose_name': 'HomePagRightContent',
                'verbose_name_plural': 'HomePagRightContent',
            },
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AlterModelOptions(
            name='hometitle',
            options={'verbose_name': 'HomeTitle', 'verbose_name_plural': 'HomeTitle'},
        ),
        migrations.RemoveField(
            model_name='hometitle',
            name='img_en',
        ),
        migrations.RemoveField(
            model_name='hometitle',
            name='img_hy',
        ),
        migrations.RemoveField(
            model_name='hometitle',
            name='img_ru',
        ),
    ]
