# Generated by Django 4.2 on 2023-04-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepageleftcontent_homepagerightcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageleftcontent',
            name='img',
        ),
        migrations.AddField(
            model_name='homepageleftcontent',
            name='text',
            field=models.TextField(default=1, verbose_name='Home Page Left Content2 Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1',
            field=models.CharField(max_length=40, verbose_name='Home Page Left Content2 Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2',
            field=models.CharField(max_length=40, verbose_name='Home Page Left Content2 Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content2 Title 2'),
        ),
    ]
