# Generated by Django 4.2 on 2023-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_homepageleftcontent_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLeftContent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40, verbose_name='Home Page Left Content2 Title 1')),
                ('title2', models.CharField(max_length=40, verbose_name='Home Page Left Content2 Title 2')),
                ('text', models.TextField(verbose_name='Home Page Left Content2 Text')),
            ],
            options={
                'verbose_name': 'HomePageLeftContent2',
                'verbose_name_plural': 'HomePageLeftContent2',
            },
        ),
        migrations.RemoveField(
            model_name='homepageleftcontent',
            name='text',
        ),
        migrations.AddField(
            model_name='homepageleftcontent',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Home Page Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1',
            field=models.CharField(max_length=40, verbose_name='Home Page Left Content Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title1_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 1'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2',
            field=models.CharField(max_length=40, verbose_name='Home Page Left Content Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2'),
        ),
        migrations.AlterField(
            model_name='homepageleftcontent',
            name='title2_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Left Content Title 2'),
        ),
    ]
