# Generated by Django 4.2 on 2023-04-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepagecontent2_delete_homepageleftcontent2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent2',
            name='btn_name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Home Page Content2 Button Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='btn_name_hy',
            field=models.CharField(max_length=25, null=True, verbose_name='Home Page Content2 Button Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='btn_name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Home Page Content2 Button Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Home Page Content2 Text'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Home Page Content2 Text'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Home Page Content2 Text'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title1_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title1_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title1_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title2_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 2'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title2_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 2'),
        ),
        migrations.AddField(
            model_name='homepagecontent2',
            name='title2_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Home Page Content2 Title 2'),
        ),
    ]
