# Generated by Django 4.2 on 2023-04-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homepagecontent2_btn_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContactGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40, verbose_name='Home ContactGet Title 1')),
                ('title1_hy', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 1')),
                ('title1_ru', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 1')),
                ('title1_en', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 1')),
                ('title2', models.CharField(max_length=40, verbose_name='Home ContactGet Title 2')),
                ('title2_hy', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 2')),
                ('title2_ru', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 2')),
                ('title2_en', models.CharField(max_length=40, null=True, verbose_name='Home ContactGet Title 2')),
                ('name', models.CharField(max_length=30, verbose_name='Home ContactGet Name')),
                ('name_hy', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Home ContactGet Surname')),
                ('surname_hy', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Surname')),
                ('surname_ru', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Surname')),
                ('surname_en', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Surname')),
                ('email', models.EmailField(max_length=30, verbose_name='Home ContactGet Email')),
                ('email_hy', models.EmailField(max_length=30, null=True, verbose_name='Home ContactGet Email')),
                ('email_ru', models.EmailField(max_length=30, null=True, verbose_name='Home ContactGet Email')),
                ('email_en', models.EmailField(max_length=30, null=True, verbose_name='Home ContactGet Email')),
                ('subject', models.CharField(max_length=30, verbose_name='Home ContactGet Subject')),
                ('subject_hy', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Subject')),
                ('subject_ru', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Subject')),
                ('subject_en', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Subject')),
                ('message', models.TextField(verbose_name='Home ContactGet Message')),
                ('message_hy', models.TextField(null=True, verbose_name='Home ContactGet Message')),
                ('message_ru', models.TextField(null=True, verbose_name='Home ContactGet Message')),
                ('message_en', models.TextField(null=True, verbose_name='Home ContactGet Message')),
                ('btn_name', models.CharField(max_length=30, verbose_name='Home ContactGet Button')),
                ('btn_name_hy', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Button')),
                ('btn_name_ru', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Button')),
                ('btn_name_en', models.CharField(max_length=30, null=True, verbose_name='Home ContactGet Button')),
                ('img', models.ImageField(upload_to='images', verbose_name='Home ContactGet Image')),
            ],
            options={
                'verbose_name': 'HomeContactGet',
                'verbose_name_plural': 'HomeContactGet',
            },
        ),
    ]
