# Generated by Django 4.2 on 2023-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutcontent2info_alter_aboutcontent2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLastContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='About Last Content Title')),
                ('title_hy', models.CharField(max_length=60, null=True, verbose_name='About Last Content Title')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='About Last Content Title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='About Last Content Title')),
                ('btn_name', models.CharField(max_length=30, verbose_name='About Last Content Button Name')),
                ('btn_name_hy', models.CharField(max_length=30, null=True, verbose_name='About Last Content Button Name')),
                ('btn_name_ru', models.CharField(max_length=30, null=True, verbose_name='About Last Content Button Name')),
                ('btn_name_en', models.CharField(max_length=30, null=True, verbose_name='About Last Content Button Name')),
            ],
        ),
    ]
