# Generated by Django 4.2 on 2023-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutlastcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent2info',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='About Content 2 Image'),
            preserve_default=False,
        ),
    ]
