# Generated by Django 4.2 on 2023-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_explorecontent_explorecontentlist_exploretitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreContent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='Explore Content 2 Text 1')),
                ('text1_hy', models.TextField(null=True, verbose_name='Explore Content 2 Text 1')),
                ('text1_ru', models.TextField(null=True, verbose_name='Explore Content 2 Text 1')),
                ('text1_en', models.TextField(null=True, verbose_name='Explore Content 2 Text 1')),
                ('text2', models.TextField(verbose_name='Explore Content 2 Text 2')),
                ('text2_hy', models.TextField(null=True, verbose_name='Explore Content 2 Text 2')),
                ('text2_ru', models.TextField(null=True, verbose_name='Explore Content 2 Text 2')),
                ('text2_en', models.TextField(null=True, verbose_name='Explore Content 2 Text 2')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Explore Content 2 Image 1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Explore Content 2 Image 2')),
                ('title', models.CharField(max_length=40, verbose_name='Explore Content 2 Title')),
                ('title_hy', models.CharField(max_length=40, null=True, verbose_name='Explore Content 2 Title')),
                ('title_ru', models.CharField(max_length=40, null=True, verbose_name='Explore Content 2 Title')),
                ('title_en', models.CharField(max_length=40, null=True, verbose_name='Explore Content 2 Title')),
                ('text3', models.TextField(verbose_name='Explore Content 2 Text 3')),
                ('text3_hy', models.TextField(null=True, verbose_name='Explore Content 2 Text 3')),
                ('text3_ru', models.TextField(null=True, verbose_name='Explore Content 2 Text 3')),
                ('text3_en', models.TextField(null=True, verbose_name='Explore Content 2 Text 3')),
                ('left_image', models.ImageField(upload_to='images', verbose_name='Explore Content 2 Left Image')),
                ('left_title', models.CharField(max_length=60, verbose_name='Explore Content 2 Left Title')),
                ('left_title_hy', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Left Title')),
                ('left_title_ru', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Left Title')),
                ('left_title_en', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Left Title')),
                ('left_subtitle', models.CharField(max_length=50, verbose_name='Explore Content 2 Left SubTitle')),
                ('left_subtitle_hy', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Left SubTitle')),
                ('left_subtitle_ru', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Left SubTitle')),
                ('left_subtitle_en', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Left SubTitle')),
                ('right_image', models.ImageField(upload_to='images', verbose_name='Explore Content 2 Right Image')),
                ('right_title', models.CharField(max_length=60, verbose_name='Explore Content 2 Right Title')),
                ('right_title_hy', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Right Title')),
                ('right_title_ru', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Right Title')),
                ('right_title_en', models.CharField(max_length=60, null=True, verbose_name='Explore Content 2 Right Title')),
                ('right_subtitle', models.CharField(max_length=50, verbose_name='Explore Content 2 Right SubTitle')),
                ('right_subtitle_hy', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Right SubTitle')),
                ('right_subtitle_ru', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Right SubTitle')),
                ('right_subtitle_en', models.CharField(max_length=50, null=True, verbose_name='Explore Content 2 Right SubTitle')),
            ],
            options={
                'verbose_name': 'ExploreContent2',
                'verbose_name_plural': 'ExploreContent2',
            },
        ),
        migrations.CreateModel(
            name='ExploreLastContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Explore Last Content Title')),
                ('title_hy', models.CharField(max_length=60, null=True, verbose_name='Explore Last Content Title')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='Explore Last Content Title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='Explore Last Content Title')),
                ('btn_name', models.CharField(max_length=30, verbose_name='Explore Last Content Button Name')),
                ('btn_name_hy', models.CharField(max_length=30, null=True, verbose_name='Explore Last Content Button Name')),
                ('btn_name_ru', models.CharField(max_length=30, null=True, verbose_name='Explore Last Content Button Name')),
                ('btn_name_en', models.CharField(max_length=30, null=True, verbose_name='Explore Last Content Button Name')),
            ],
            options={
                'verbose_name': 'ExploreLastContent',
                'verbose_name_plural': 'ExploreLastContent',
            },
        ),
    ]
