# Generated by Django 4.2 on 2023-04-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_explorecontent2_explorelastcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorecontent2',
            old_name='left_image',
            new_name='left_img',
        ),
        migrations.RenameField(
            model_name='explorecontent2',
            old_name='right_image',
            new_name='right_img',
        ),
    ]
