# Generated by Django 4.2 on 2023-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_left_image_explorecontent2_left_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Trending Content List Title')),
                ('title_hy', models.CharField(max_length=30, null=True, verbose_name='Trending Content List Title')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Trending Content List Title')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Trending Content List Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Trending Content List Subtitle')),
                ('subtitle_hy', models.CharField(max_length=50, null=True, verbose_name='Trending Content List Subtitle')),
                ('subtitle_ru', models.CharField(max_length=50, null=True, verbose_name='Trending Content List Subtitle')),
                ('subtitle_en', models.CharField(max_length=50, null=True, verbose_name='Trending Content List Subtitle')),
                ('img', models.ImageField(upload_to='images', verbose_name='Trending Content List Image')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingLastContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Trending Last Content Title')),
                ('title_hy', models.CharField(max_length=80, null=True, verbose_name='Trending Last Content Title')),
                ('title_ru', models.CharField(max_length=80, null=True, verbose_name='Trending Last Content Title')),
                ('title_en', models.CharField(max_length=80, null=True, verbose_name='Trending Last Content Title')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Trending Last Content Button Name')),
                ('btn_name_hy', models.CharField(max_length=40, null=True, verbose_name='Trending Last Content Button Name')),
                ('btn_name_ru', models.CharField(max_length=40, null=True, verbose_name='Trending Last Content Button Name')),
                ('btn_name_en', models.CharField(max_length=40, null=True, verbose_name='Trending Last Content Button Name')),
            ],
            options={
                'verbose_name': 'TrendingLastContent',
                'verbose_name_plural': 'TrendingLastContent',
            },
        ),
        migrations.CreateModel(
            name='TrendingTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20, verbose_name='Trending Title 1')),
                ('title1_hy', models.CharField(max_length=20, null=True, verbose_name='Trending Title 1')),
                ('title1_ru', models.CharField(max_length=20, null=True, verbose_name='Trending Title 1')),
                ('title1_en', models.CharField(max_length=20, null=True, verbose_name='Trending Title 1')),
                ('title2', models.CharField(max_length=20, verbose_name='Trending Title 2')),
                ('title2_hy', models.CharField(max_length=20, null=True, verbose_name='Trending Title 2')),
                ('title2_ru', models.CharField(max_length=20, null=True, verbose_name='Trending Title 2')),
                ('title2_en', models.CharField(max_length=20, null=True, verbose_name='Trending Title 2')),
                ('text', models.TextField(verbose_name='Trending Text')),
                ('text_hy', models.TextField(null=True, verbose_name='Trending Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Trending Text')),
                ('text_en', models.TextField(null=True, verbose_name='Trending Text')),
            ],
            options={
                'verbose_name': 'TrendingTitle',
                'verbose_name_plural': 'TrendingTitle',
            },
        ),
    ]
