# Generated by Django 4.2 on 2023-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_trendingcontentlist_subtitle_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=40, verbose_name='Contact Get SubTitle 1')),
                ('subtitle1_hy', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 1')),
                ('subtitle1_ru', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 1')),
                ('subtitle1_en', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 1')),
                ('subtitle2', models.CharField(max_length=40, verbose_name='Contact Get SubTitle 2')),
                ('subtitle2_hy', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 2')),
                ('subtitle2_ru', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 2')),
                ('subtitle2_en', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 2')),
                ('subtitle3', models.CharField(max_length=40, verbose_name='Contact Get SubTitle 3')),
                ('subtitle3_hy', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 3')),
                ('subtitle3_ru', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 3')),
                ('subtitle3_en', models.CharField(max_length=40, null=True, verbose_name='Contact Get SubTitle 3')),
                ('info1', models.CharField(max_length=60, verbose_name='Contact Get Info 1')),
                ('info1_hy', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 1')),
                ('info1_ru', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 1')),
                ('info1_en', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 1')),
                ('info2', models.CharField(max_length=60, verbose_name='Contact Get Info 2')),
                ('info2_hy', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 2')),
                ('info2_ru', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 2')),
                ('info2_en', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 2')),
                ('info3', models.CharField(max_length=60, verbose_name='Contact Get Info 3')),
                ('info3_hy', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 3')),
                ('info3_ru', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 3')),
                ('info3_en', models.CharField(max_length=60, null=True, verbose_name='Contact Get Info 3')),
            ],
            options={
                'verbose_name': 'ContactGet',
                'verbose_name_plural': 'ContactGet',
            },
        ),
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20, verbose_name='Contact Title 1')),
                ('title2', models.CharField(max_length=20, verbose_name='Contact Title 2')),
                ('text', models.TextField(verbose_name='Contact Text')),
            ],
            options={
                'verbose_name': 'ContactTitle',
                'verbose_name_plural': 'ContactTitle',
            },
        ),
    ]
