# Generated by Django 4.2 on 2023-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactget_contacttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttitle',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Contact Text'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Contact Text'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Contact Text'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title1_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 1'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title1_hy',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 1'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title1_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 1'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title2_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 2'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title2_hy',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 2'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='title2_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Contact Title 2'),
        ),
    ]
