# Generated by Django 4.2 on 2023-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_contactget_info2_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='User Name')),
                ('user_surname', models.CharField(max_length=40, verbose_name='User Surname')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('user_subject', models.CharField(max_length=50, verbose_name='User Subject')),
                ('user_message', models.TextField(verbose_name='User Message')),
            ],
        ),
    ]
